### ISSUE TITLE
Conda env build fails building pydensecrf from pip

### ISSUE THREAD

**Issue by ddbuscombe** [dbuscombe-usgs/holodoodler#5]
The current conda environment fails when installing the pip version of `pydensecrf`

The solution is to use the conda package. I propose we use following yml file 

```
name: holodoodler
channels:
  - conda-forge
  - defaults
dependencies:
 - python
 - tifffile
 - CairoSVG
 - matplotlib
 - scipy
 - numpy
 - scikit-image
 - Pillow
 - scikit-learn
 - cairo
 - tqdm
 - psutil
 - jupyterlab
 - holoviews
 - panel
 - flake8
 - pytest
 - pytest-cov
 - plotly
 - gdal
 - pydensecrf
 - pip
 - pip:
   - doodler-engine
```

(also note the new conda env name `holodoodler`, which is easier to remember and more descriptive)

**Comment by venuswku** [comment]
I tested creating a conda environment with the proposed yml file and it works for me too! Your changes have been included in both of my recent PRs (https://github.com/Doodleverse/holodoodler/pull/11 and https://github.com/Doodleverse/holodoodler/pull/12) so merging either one of them should also close this issue. Both PRs are tested and ready for merging.
I've also been trying to create a conda recipe as an alternative but haven't been able to do so successfully yet due to a `gdal` import error. Going to create a new issue for that soon!

**Comment by ddbuscombe** [comment]
Nice work @venuswku I believe we can now close this issue
